spring:
  application:
    name: climalert
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmailplaceholder@gmail.com
    password: passwordplaceholder
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
weather-api:
  base-url: https://api.weatherapi.com/v1
  method: /current.json
  key: 2006e47f9949457887a234240262806
  city-name: Buenos Aires
